@id = 7f503fff-a4a7-4b36-8039-dc98e05c6f70

PUT http://localhost:5024/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine By Zubair",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}